import { FaAws, FaJava, FaGitlab, FaTrello } from "react-icons/fa";
import {
    SiHtml5,
    SiReact,
    SiGithub,
    SiNodedotjs,
    SiGit,
    SiMongodb,
    SiTailwindcss,
    SiTypescript,
    SiNextdotjs,
    SiOpenai,
    SiPostman,
    SiCss3,
    SiShadcnui,
    SiJira,
    SiMui,
    SiJavascript,
    SiEslint,
    SiWebflow,
    SiElementor,
    SiMysql,
    SiWordpress,
    SiSvelte,
    SiPython,
    SiStrapi,
    SiPostgresql,
    SiPrisma,
    // SiApi,
    SiDocker,
    SiAxios,
    SiLucide,
    SiSupabase,
    SiExpress,
    SiVercel,
    SiVite,
    SiCloudflare,
    SiAdobepremierepro,
    SiAdobeaftereffects,
    SiAdobephotoshop,
    SiPrettier,
} from "react-icons/si";
import { TbBrandVscode } from "react-icons/tb";
import { BiGitBranch, BiCodeCurly } from "react-icons/bi";
import { RiCodeSSlashFill } from "react-icons/ri";
import { BsPcDisplay } from "react-icons/bs";
import { TbCloudCog } from "react-icons/tb";
import { DiHeroku } from "react-icons/di";
import { CursorIcon } from "./cursorIcon";
import { CursorIconWhite } from "./cursorIconWhite";

// Create a mapping for icons
export const iconMap = {
    aftereffects: SiAdobeaftereffects,
    aws: FaAws,
    axios: SiAxios,
    cloudflare: SiCloudflare,
    code: RiCodeSSlashFill,
    css: SiCss3,
    cursor: CursorIcon,
    cursorwhite: CursorIconWhite,
    curly: BiCodeCurly,
    docker: SiDocker,
    elementor: SiElementor,
    eslint: SiEslint,
    express: SiExpress,
    git: SiGit,
    github: SiGithub,
    gitlab: FaGitlab,
    heroku: DiHeroku,
    html: SiHtml5,
    java: FaJava,
    javascript: SiJavascript,
    jira: SiJira,
    lucide: SiLucide,
    mongodb: SiMongodb,
    mui: SiMui,
    mysql: SiMysql,
    next: SiNextdotjs,
    node: SiNodedotjs,
    openai: SiOpenai,
    pc: BsPcDisplay,
    photoshop: SiAdobephotoshop,
    postgresql: SiPostgresql,
    postman: SiPostman,
    premiere: SiAdobepremierepro,
    prettier: SiPrettier,
    prisma: SiPrisma,
    python: SiPython,
    react: SiReact,
    restapi: TbCloudCog,
    shadcn: SiShadcnui,
    sourcetree: BiGitBranch,
    strapi: SiStrapi,
    supabase: SiSupabase,
    svelte: SiSvelte,
    tailwind: SiTailwindcss,
    trello: FaTrello,
    typescript: SiTypescript,
    vercel: SiVercel,
    vite: SiVite,
    vscode: TbBrandVscode,
    webflow: SiWebflow,
    wordpress: SiWordpress,
};
