import { FaAws, FaJava, FaGitlab, FaTrello } from "react-icons/fa";
import {
    SiHtml5,
    SiReact,
    SiGithub,
    SiNodedotjs,
    SiGit,
    SiMongodb,
    SiTailwindcss,
    SiTypescript,
    SiNextdotjs,
    SiOpenai,
    SiPostman,
    SiCss3,
    SiShadcnui,
    SiJira,
    SiMui,
    SiJavascript,
    SiEslint,
    SiWebflow,
    SiElementor,
    SiMysql,
    SiWordpress,
    SiSvelte,
    SiPython,
    SiStrapi,
    SiPostgresql,
    SiPrisma,
    // SiApi,
    SiDocker,
    SiAxios,
    SiLucide,
    SiSupabase,
    SiExpress,
    SiVercel,
    SiVite,
    SiCloudflare,
    SiAdobepremierepro,
    SiAdobeaftereffects,
    SiAdobephotoshop,
    SiPrettier,
    SiStripe,
    SiDrizzle,
    SiReactquery,
    SiSentry,
    SiZod,
    SiJest,
    SiPassport,
    SiSendgrid,
    SiRadixui,
    SiCapacitor,
    SiClaude,
    SiElectron,
    SiFirebase,
    SiResend,
} from "react-icons/si";
import { TbBrandVscode } from "react-icons/tb";
import { BiGitBranch, BiCodeCurly } from "react-icons/bi";
import { RiCodeSSlashFill } from "react-icons/ri";
import { BsPcDisplay } from "react-icons/bs";
import { TbCloudCog } from "react-icons/tb";
import { DiHeroku } from "react-icons/di";
import { CursorIcon } from "./cursorIcon";
import { CursorIconWhite } from "./cursorIconWhite";

// Create a mapping for icons
export const iconMap = {
    aftereffects: SiAdobeaftereffects,
    aws: FaAws,
    axios: SiAxios,
    capacitor: SiCapacitor,
    claude: SiClaude,
    cloudflare: SiCloudflare,
    code: RiCodeSSlashFill,
    css: SiCss3,
    cursor: CursorIcon,
    cursorwhite: CursorIconWhite,
    curly: BiCodeCurly,
    docker: SiDocker,
    electron: SiElectron,
    elementor: SiElementor,
    eslint: SiEslint,
    express: SiExpress,
    firebase: SiFirebase,
    git: SiGit,
    github: SiGithub,
    gitlab: FaGitlab,
    heroku: DiHeroku,
    html: SiHtml5,
    java: FaJava,
    javascript: SiJavascript,
    jira: SiJira,
    lucide: SiLucide,
    mongodb: SiMongodb,
    mui: SiMui,
    mysql: SiMysql,
    next: SiNextdotjs,
    node: SiNodedotjs,
    openai: SiOpenai,
    pc: BsPcDisplay,
    photoshop: SiAdobephotoshop,
    postgresql: SiPostgresql,
    postman: SiPostman,
    premiere: SiAdobepremierepro,
    prettier: SiPrettier,
    prisma: SiPrisma,
    python: SiPython,
    stripe: SiStripe,
    drizzle: SiDrizzle,
    reactquery: SiReactquery,
    sentry: SiSentry,
    zod: SiZod,
    jest: SiJest,
    passport: SiPassport,
    react: SiReact,
    radix: SiRadixui,
    resend: SiResend,
    restapi: TbCloudCog,
    sendgrid: SiSendgrid,
    shadcn: SiShadcnui,
    sourcetree: BiGitBranch,
    strapi: SiStrapi,
    supabase: SiSupabase,
    svelte: SiSvelte,
    tailwind: SiTailwindcss,
    trello: FaTrello,
    typescript: SiTypescript,
    vercel: SiVercel,
    vite: SiVite,
    vscode: TbBrandVscode,
    webflow: SiWebflow,
    wordpress: SiWordpress,
};

// Official-ish brand colors for the per-project tech icons. Monochrome / near-black
// brands (github, next, vercel, express, prisma-dark, shadcn, radix, resend, cursor…)
// are intentionally omitted so they inherit the container color and stay legible in
// both light and dark mode.
export const brandColors: Record<string, string> = {
    claude: "#D97757",
    react: "#61DAFB",
    typescript: "#3178C6",
    javascript: "#F7DF1E",
    vite: "#646CFF",
    tailwind: "#06B6D4",
    node: "#5FA04E",
    postgresql: "#4169E1",
    mongodb: "#47A248",
    mysql: "#4479A1",
    supabase: "#3FCF8E",
    drizzle: "#C5F74F",
    openai: "#412991",
    stripe: "#635BFF",
    reactquery: "#FF4154",
    sentry: "#8949FF",
    zod: "#3E67B1",
    eslint: "#4B32C3",
    prettier: "#F7B93E",
    git: "#F05032",
    gitlab: "#FC6D26",
    vscode: "#007ACC",
    css: "#1572B6",
    html: "#E34F26",
    python: "#3776AB",
    java: "#F89820",
    axios: "#5A29E4",
    mui: "#007FFF",
    aws: "#FF9900",
    trello: "#0052CC",
    jira: "#0052CC",
    sourcetree: "#0052CC",
    postman: "#FF6C37",
    capacitor: "#119EFF",
    cloudflare: "#F38020",
    docker: "#2496ED",
    firebase: "#FFA000",
    electron: "#47848F",
    lucide: "#F56565",
    svelte: "#FF3E00",
    strapi: "#4945FF",
    passport: "#34E27A",
    sendgrid: "#1A82E2",
    jest: "#C21325",
    heroku: "#430098",
    wordpress: "#21759B",
    webflow: "#146EF5",
    elementor: "#92003B",
    premiere: "#9999FF",
    photoshop: "#31A8FF",
    aftereffects: "#9999FF",
};
